### PR TITLE
Add inspect functionality.

### PR DESCRIPTION
**Pull request by relaxnow**
Most of this code is blatantly stolen from 'deposit'.
This is my first PR, let me know what needs improving.

### CODE REVIEW

**Comment by orval** [comment]
Thanks for this! Very much appreciated 🙏 

I took "inspect" to mean it would show me something. Although not added to the TODOs, I did wonder about adding a `lint` command in the past -- perhaps `inspect` could be changed to `lint`.

I'd prefer no duplication of code. It would be good to see a dry-run or read-only flag passed to `deposit()` and have the new command call that.

Please also add something to `docs/cli` about the new command.

**Comment by relaxnow** [comment]
I called it `lint` but then changed it to `inspect` to fit the theme better. 😄

`deposit --dry-run` could also work.

**Comment by relaxnow** [comment]
Parking this for now until the next time I need it.

**Comment by orval** [comment]
Thanks for this idea. I chose to make an enhancement to the existing `fs` command, so one can lint with:
```
rakosh -v fs lint <dir>
```

**Pull request closed without merging**
